apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment2
  labels:
    app: node-app-viettq2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-viettq2
  template:
    metadata:
      labels:
        app: node-app-viettq2
    spec:
      containers:
        - name: node-app2
          image: harbor.host/nodejs-demo/my-app
          imagePullPolicy: Always
          resources:
            # Specifying the resourses that we might need for our application
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
      imagePullSecrets:
        - name: registry
